//
//  MapWorker.swift
//  TreeClimbr
//
//  Created by Mar Koss on 2019-03-23.
//  Copyright (c) 2019 Mar Koss. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MapWorker
{
  func doSomeWork()
  {
  }
}
